### ISSUE TITLE
oc bash completion doesn't take into affect abbreviated options like -n

### ISSUE THREAD

**Issue by nabbas-ca** [openshift/oc#1342] opened 2023-02-15 04:20 UTC
```
[root@roadieag5 mgen-hci-automation]# oc --namespace test-db2 get po
c-isd-db2u-0                            c-isd-graph-6fb49969fd-fdqx6            c-isd-ldap-9494d7f66-2v7z5              c-isd-restore-morph-nmqjg               db2u-operator-manager-6d56db97d4-9fx8l
c-isd-etcd-0                            c-isd-instdb-5bbw6                      c-isd-rest-88bb5c76f-v2vk5              c-isd-tools-ff67db6cd-pvj86
```

vs 

```
[root@roadieag5 mgen-hci-automation]# oc -n test-db2 get po
```
which does nothing and displays local files

**Comment by ardaguclu** [comment] 2023-02-21 12:11
Thanks for opening this issue.

it looks duplicate of https://github.com/kubernetes/kubectl/issues/1367. Basically, this works as intended and more info are in the referenced issue.

I'm closing this one and feel free to re-open it, if I'm missing something.

/close

**Closed** 2023-02-21 12:11 UTC
